# Generated by Django 3.0.4 on 2020-04-05 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ampapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppModel',
            new_name='AmpModel',
        ),
    ]
