# Generated by Django 3.0.4 on 2020-04-17 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ampapp', '0005_auto_20200417_0704'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name_plural': 'answer'},
        ),
    ]
