# Generated by Django 3.0.4 on 2020-04-18 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ampapp', '0006_auto_20200417_1234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name_plural': 'Answer'},
        ),
    ]
