# Generated by Django 3.0.4 on 2020-04-21 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ampapp', '0007_auto_20200418_0551'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='diary',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to='ampapp.Diary'),
            preserve_default=False,
        ),
    ]
