# Generated by Django 3.0.4 on 2020-04-21 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ampapp', '0010_answer_diary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='diary',
        ),
    ]
