# Generated by Django 3.0.4 on 2020-04-22 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ampapp', '0013_auto_20200421_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='readtext',
            field=models.CharField(max_length=40, null=True, verbose_name='いいね'),
        ),
    ]
