# Generated by Django 3.0.4 on 2020-04-22 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ampapp', '0014_diary_readtext'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='read',
            field=models.IntegerField(null=True),
        ),
    ]
