# Generated by Django 3.0.4 on 2020-04-22 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ampapp', '0016_auto_20200422_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='read',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
