# Generated by Django 3.0.4 on 2020-04-23 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ampapp', '0021_auto_20200423_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ine',
            name='read',
        ),
        migrations.RemoveField(
            model_name='ine',
            name='readtext',
        ),
        migrations.AlterField(
            model_name='ine',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ampapp.Answer'),
        ),
    ]
