# Generated by Django 3.0.4 on 2020-04-24 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ampapp', '0022_auto_20200423_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='read',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ine',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ampapp.Answer'),
        ),
    ]
