# Generated by Django 3.0.4 on 2020-04-26 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ampapp', '0026_auto_20200425_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='read',
        ),
        migrations.AddField(
            model_name='answer',
            name='articles_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.DeleteModel(
            name='Ine',
        ),
    ]
