# Generated by Django 3.0.4 on 2020-04-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ampapp', '0027_auto_20200426_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='read',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
