# Generated by Django 3.0.4 on 2020-04-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ampapp', '0029_answer_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='readtext',
            field=models.CharField(blank=True, default='a', max_length=100, null=True),
        ),
    ]
