# Generated by Django 3.0.4 on 2020-04-29 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ampapp', '0031_diary_vi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diary',
            old_name='vi',
            new_name='views',
        ),
    ]
