# Generated by Django 3.0.4 on 2020-04-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ampapp', '0032_auto_20200429_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='good',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='diary',
            name='readtext',
            field=models.CharField(blank=True, default='a', max_length=100, null=True),
        ),
    ]
