# Generated by Django 3.0.4 on 2020-04-29 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ampapp', '0033_auto_20200429_2301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diary',
            old_name='readtext',
            new_name='goodtext',
        ),
    ]
