# Generated by Django 3.0.4 on 2020-04-30 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ampapp', '0034_auto_20200429_2307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='articles_id',
            new_name='best',
        ),
    ]
