# Generated by Django 3.0.4 on 2020-05-01 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ampapp', '0036_auto_20200501_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='readtext',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
