# Generated by Django 3.0.4 on 2020-05-01 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ampapp', '0039_auto_20200501_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='readtext',
            field=models.CharField(blank=True, default='a', max_length=100, null=True),
        ),
    ]
