# Generated by Django 3.0.4 on 2020-05-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ampapp', '0040_auto_20200501_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='iine',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
