# Generated by Django 3.0.4 on 2020-05-02 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ampapp', '0041_answer_iine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='iine',
        ),
        migrations.CreateModel(
            name='Ine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kidoku', models.IntegerField(blank=True, default=0, null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ampapp.Answer')),
            ],
            options={
                'verbose_name_plural': 'Ine',
            },
        ),
    ]
