# Generated by Django 3.0.4 on 2020-05-02 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ampapp', '0042_auto_20200502_0944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ine',
            name='parent',
        ),
    ]
