# Generated by Django 3.0.4 on 2020-05-02 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ampapp', '0043_remove_ine_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='ine',
            name='parent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ampapp.Answer'),
            preserve_default=False,
        ),
    ]
