# Generated by Django 3.0.4 on 2020-05-02 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ampapp', '0048_auto_20200502_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ine',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='ine',
            name='user',
        ),
    ]
