# Generated by Django 3.0.4 on 2020-05-02 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ampapp', '0051_auto_20200502_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ine',
            name='user',
        ),
        migrations.AlterField(
            model_name='ine',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ampapp.Answer'),
        ),
    ]
