# Generated by Django 3.0.4 on 2020-05-02 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ampapp', '0052_auto_20200502_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ine',
            name='answer',
        ),
        migrations.AddField(
            model_name='ine',
            name='kid',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
