# Generated by Django 3.0.4 on 2020-05-09 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ampapp', '0055_auto_20200509_1036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamea',
            old_name='game',
            new_name='gameq',
        ),
    ]
