# Generated by Django 3.0.4 on 2020-05-10 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ampapp', '0057_studya_studyine_studyq'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studya',
            options={'verbose_name_plural': 'Studya'},
        ),
        migrations.AlterModelOptions(
            name='studyine',
            options={'verbose_name_plural': 'Studyine'},
        ),
        migrations.AlterModelOptions(
            name='studyq',
            options={'verbose_name_plural': 'Studyq'},
        ),
        migrations.RemoveField(
            model_name='answer',
            name='readtext',
        ),
        migrations.RemoveField(
            model_name='diary',
            name='good',
        ),
        migrations.RemoveField(
            model_name='diary',
            name='goodtext',
        ),
        migrations.RemoveField(
            model_name='diary',
            name='views',
        ),
        migrations.RemoveField(
            model_name='gamea',
            name='readtext',
        ),
        migrations.RemoveField(
            model_name='gameq',
            name='good',
        ),
        migrations.RemoveField(
            model_name='gameq',
            name='goodtext',
        ),
        migrations.RemoveField(
            model_name='gameq',
            name='views',
        ),
        migrations.RemoveField(
            model_name='studya',
            name='readtext',
        ),
        migrations.RemoveField(
            model_name='studyq',
            name='good',
        ),
        migrations.RemoveField(
            model_name='studyq',
            name='goodtext',
        ),
        migrations.RemoveField(
            model_name='studyq',
            name='views',
        ),
    ]
