# Generated by Django 3.0.4 on 2020-05-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ampapp', '0068_auto_20200515_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='ip_address',
            field=models.CharField(default=1, max_length=20, verbose_name='IPアドレス'),
            preserve_default=False,
        ),
    ]
