# Generated by Django 3.0.4 on 2020-05-16 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ampapp', '0070_auto_20200515_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameq',
            name='name',
            field=models.CharField(default=1, max_length=40, verbose_name='タイトル'),
            preserve_default=False,
        ),
    ]
