# Generated by Django 3.0.4 on 2020-05-16 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ampapp', '0071_gameq_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameq',
            name='name',
            field=models.CharField(max_length=40, verbose_name='名前'),
        ),
    ]
