# Generated by Django 3.0.4 on 2020-05-16 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ampapp', '0073_diary_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifeq',
            name='name',
            field=models.CharField(default=1, max_length=40, verbose_name='名前'),
            preserve_default=False,
        ),
    ]
