# Generated by Django 3.0.4 on 2020-05-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ampapp', '0081_auto_20200516_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameq',
            name='ip_address',
            field=models.CharField(default=1, max_length=20, verbose_name='IPアドレス'),
            preserve_default=False,
        ),
    ]
