# Generated by Django 3.0.6 on 2020-05-30 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ampapp', '0095_auto_20200516_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='content',
            field=models.TextField(default=1, verbose_name='本文'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='diary',
            name='content',
            field=models.TextField(null=True, verbose_name='本文'),
        ),
        migrations.AlterField(
            model_name='futurea',
            name='content',
            field=models.TextField(null=True, verbose_name='本文'),
        ),
        migrations.AlterField(
            model_name='futureq',
            name='content',
            field=models.TextField(null=True, verbose_name='本文'),
        ),
        migrations.AlterField(
            model_name='gamea',
            name='content',
            field=models.TextField(default=1, verbose_name='本文'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gameq',
            name='content',
            field=models.TextField(default=1, verbose_name='本文'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='healtha',
            name='content',
            field=models.TextField(null=True, verbose_name='本文'),
        ),
        migrations.AlterField(
            model_name='healthq',
            name='content',
            field=models.TextField(null=True, verbose_name='本文'),
        ),
        migrations.AlterField(
            model_name='hobbya',
            name='content',
            field=models.TextField(null=True, verbose_name='本文'),
        ),
        migrations.AlterField(
            model_name='hobbyq',
            name='content',
            field=models.TextField(null=True, verbose_name='本文'),
        ),
        migrations.AlterField(
            model_name='jokea',
            name='content',
            field=models.TextField(null=True, verbose_name='本文'),
        ),
        migrations.AlterField(
            model_name='jokeq',
            name='content',
            field=models.TextField(null=True, verbose_name='本文'),
        ),
        migrations.AlterField(
            model_name='lifea',
            name='content',
            field=models.TextField(null=True, verbose_name='本文'),
        ),
        migrations.AlterField(
            model_name='lifeq',
            name='content',
            field=models.TextField(null=True, verbose_name='本文'),
        ),
        migrations.AlterField(
            model_name='occulta',
            name='content',
            field=models.TextField(null=True, verbose_name='本文'),
        ),
        migrations.AlterField(
            model_name='occultq',
            name='content',
            field=models.TextField(null=True, verbose_name='本文'),
        ),
        migrations.AlterField(
            model_name='sciencea',
            name='content',
            field=models.TextField(null=True, verbose_name='本文'),
        ),
        migrations.AlterField(
            model_name='scienceq',
            name='content',
            field=models.TextField(null=True, verbose_name='本文'),
        ),
        migrations.AlterField(
            model_name='studya',
            name='content',
            field=models.TextField(null=True, verbose_name='本文'),
        ),
        migrations.AlterField(
            model_name='studyq',
            name='content',
            field=models.TextField(null=True, verbose_name='本文'),
        ),
        migrations.AlterField(
            model_name='talenta',
            name='content',
            field=models.TextField(null=True, verbose_name='本文'),
        ),
        migrations.AlterField(
            model_name='talentq',
            name='content',
            field=models.TextField(null=True, verbose_name='本文'),
        ),
        migrations.AlterField(
            model_name='worka',
            name='content',
            field=models.TextField(null=True, verbose_name='本文'),
        ),
        migrations.AlterField(
            model_name='workq',
            name='content',
            field=models.TextField(null=True, verbose_name='本文'),
        ),
    ]
