# Generated by Django 3.0.6 on 2020-05-30 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ampapp', '0096_auto_20200530_1820'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ine',
        ),
    ]
