# Generated by Django 3.0.6 on 2020-05-30 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ampapp', '0097_delete_ine'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gameine',
        ),
    ]
