# Generated by Django 3.0.6 on 2020-05-30 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ampapp', '0098_delete_gameine'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Scienceine',
        ),
        migrations.DeleteModel(
            name='Studyine',
        ),
    ]
