# Generated by Django 3.0.6 on 2020-05-30 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ampapp', '0099_auto_20200530_2157'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Futureine',
        ),
        migrations.DeleteModel(
            name='Healthine',
        ),
        migrations.DeleteModel(
            name='Talentine',
        ),
    ]
