# Generated by Django 3.0.6 on 2020-05-30 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ampapp', '0100_auto_20200530_2159'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hobbyine',
        ),
        migrations.DeleteModel(
            name='Jokeine',
        ),
        migrations.DeleteModel(
            name='Lifeine',
        ),
        migrations.DeleteModel(
            name='Occultine',
        ),
        migrations.DeleteModel(
            name='Workine',
        ),
    ]
